In [40]:
import csv
import pandas as pd

data = pd.read_csv('/Users/winnergogo/Desktop/DB/bank_withname.csv')
# data
header = list(data.columns.values)
header
data

name  age   marital education  balance housing loan  \
0           David Meunier   58   married        BS     2143     yes   no   
1           Robbie Joseph   44    single        MS       29     yes   no   
2           Teresa Morgan   33   married        MS        2     yes  yes   
3          Glenn Anderson   47   married   unknown     1506     yes   no   
4           Trent Morales   33    single   unknown        1      no   no   
5           Janet Viernes   35   married        BS      231     yes   no   
6               Adam Puhl   28    single        BS      447     yes  yes   
7           Michael Jones   42  divorced        BS        2     yes   no   
8             Oscar Laird   58   married       PhD      121     yes   no   
9            Robert Kuehn   43    single        MS      593     yes   no   
10          Gerald Waites   41  divorced        MS      270     yes   no   
11        Brenda Mitchell   29    single        MS      390     yes   no   
12             Ivan Brady   53   married        MS        6     yes   no   
13             John Compo   58   married   unknown       71     yes   no   
14           Kevin Gerdes   57   married        MS      162     yes   no   
15        Nicholas Trahan   51   married       PhD      229     yes   no   
16            Gordon Cook   45    single   unknown       13     yes   no   
17         Daniel Voegele   57   married       PhD       52     yes   no   
18             Judy Grier   60   married       PhD       60     yes   no   
19           Alice Kelley   33   married        MS        0     yes   no   
20         Benjamin Shipp   28   married        MS      723     yes  yes   
21           Tina Hadaway   56   married        BS      779     yes   no   
22          Bernard Berry   32    single       PhD       23     yes  yes   
23          Evelyn Covert   25   married        MS       50     yes   no   
24           Nora Nichols   40   married       PhD        0     yes  yes   
25         Barbara Torrez   44   married        MS     -372     yes   no   
26           Edward Casey   39    single        BS      255     yes   no   
27             Carrie May   52   married        MS      113     yes  yes   
28            Sung Turner   46    single        MS     -246     yes   no   
29           Paula Gustin   36    single        MS      265     yes  yes   
...                   ...  ...       ...       ...      ...     ...  ...   
45181        Mark Charron   46   married        MS     6879      no   no   
45182       Mathew Carter   34   married        MS      133      no   no   
45183        Mike Sampson   70   married       PhD      324      no   no   
45184          Jon Brooks   63   married        MS     1495      no   no   
45185       Floyd Winters   60   married        BS     4256     yes   no   
45186            Rey Kamm   59   married   unknown     1500      no   no   
45187     Patricia Landry   32    single        MS     1168     yes   no   
45188         Carlos Kain   29    single        MS      703     yes   no   
45189       Brian Bradley   25    single        MS      199      no   no   
45190        Karl Caudill   32   married        MS      136      no   no   
45191    Cynthia Kilkenny   75  divorced        BS     3810     yes   no   
45192      Estelle Glover   29    single        BS      765      no   no   
45193      Gloria Kincaid   28    single        BS      159      no   no   
45194    Jonathan Hamblin   59   married        BS      138     yes  yes   
45195         James Smuin   68   married        MS     1146      no   no   
45196       Misty Carroll   25    single        MS      358      no   no   
45197       Melissa Hobdy   36    single        MS     1511     yes   no   
45198      Lawrence Soape   37   married        BS     1428      no   no   
45199     Kevin Goldstein   34    single        MS     1475     yes   no   
45200    Loretta Manalang   38   married        MS      557     yes   no   
45201          Dean Prada   53   married        BS      583      no  

In [80]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.neighbors import KNeighborsClassifier
train_df = pd.read_csv('/Users/winnergogo/Desktop/DB/bank_withname.csv')  

train_df = train_df.drop(['name'], axis=1)

ages = train_df['age']

train_df['marital'] = train_df['marital'].replace('married',0)
train_df['marital'] = train_df['marital'].replace('single',1)
train_df['marital'] = train_df['marital'].replace('divorced',2)
train_df['marital'] = train_df['marital'].replace('unknown',3)

train_df['education'] = train_df['education'].replace('MS',0)
train_df['education'] = train_df['education'].replace('PhD',1)
train_df['education'] = train_df['education'].replace('BS',2)
train_df['education'] = train_df['education'].replace('unknown',3)

train_df['housing'] = train_df['housing'].replace('no',0)
train_df['housing'] = train_df['housing'].replace('yes',1)
train_df['housing'] = train_df['housing'].replace('unknown',2)

train_df['loan'] = train_df['loan'].replace('no',0)
train_df['loan'] = train_df['loan'].replace('yes',1)
train_df['loan'] = train_df['loan'].replace('unknown',2)


balances = train_df['balance']
durations = train_df['duration']

y_train = train_df['y']
y_train = y_train.replace('no',0)
y_train = y_train.replace('yes',1)

train_df = train_df.drop(['y'], axis=1)

# train_df
# y_train

In [81]:
train_df = train_df.values
# print(train_df)

In [94]:
y_train = y_train.values
# print(y_train)

In [95]:
import keras
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation

model = Sequential()

model.add(Dense(units=16, input_dim=7, 
                activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(units=32, 
                activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(units=256, 
                activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(units=1,
                activation='sigmoid'))
                    
model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_15 (Dense)             (None, 16)                128       
_________________________________________________________________
dropout_4 (Dropout)          (None, 16)                0         
_________________________________________________________________
dense_16 (Dense)             (None, 32)                544       
_________________________________________________________________
dropout_5 (Dropout)          (None, 32)                0         
_________________________________________________________________
dense_17 (Dense)             (None, 256)               8448      
_________________________________________________________________
dropout_6 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_18 (Dense)             (None, 1)                 257       
Total para

In [106]:
model.compile(loss='binary_crossentropy', 
              optimizer='adam', metrics=['accuracy'])

model.fit(train_df, y_train,batch_size=1024, 
         epochs=50,verbose=2,validation_split=0.2)

Train on 36168 samples, validate on 9043 samples
Epoch 1/50
 - 1s - loss: 0.1954 - acc: 0.9344 - val_loss: 0.8829 - val_acc: 0.6868
Epoch 2/50
 - 0s - loss: 0.1950 - acc: 0.9350 - val_loss: 0.9187 - val_acc: 0.6842
Epoch 3/50
 - 0s - loss: 0.1948 - acc: 0.9350 - val_loss: 0.8882 - val_acc: 0.6869
Epoch 4/50
 - 0s - loss: 0.1929 - acc: 0.9351 - val_loss: 0.9008 - val_acc: 0.6842
Epoch 5/50
 - 0s - loss: 0.1918 - acc: 0.9340 - val_loss: 0.9306 - val_acc: 0.6845
Epoch 6/50
 - 0s - loss: 0.1900 - acc: 0.9342 - val_loss: 0.9207 - val_acc: 0.6843
Epoch 7/50
 - 0s - loss: 0.1903 - acc: 0.9350 - val_loss: 0.8651 - val_acc: 0.6890
Epoch 8/50
 - 0s - loss: 0.1904 - acc: 0.9341 - val_loss: 0.8731 - val_acc: 0.6846
Epoch 9/50
 - 0s - loss: 0.1896 - acc: 0.9349 - val_loss: 0.9201 - val_acc: 0.6847
Epoch 10/50
 - 0s - loss: 0.1891 - acc: 0.9347 - val_loss: 0.9275 - val_acc: 0.6843
Epoch 11/50
 - 0s - loss: 0.1898 - acc: 0.9348 - val_loss: 0.8888 - val_acc: 0.6838
Epoch 12/50
 - 0s - loss: 0.1897 - a

In [107]:
scores = model.evaluate(x=train_df, 
                        y=y_train)
scores[1]

45211/45211 [==============================] - 1s 26us/step


0.88319214350621766

In [108]:
import numpy as np
x_test = [[72,0,0,5715,0,0,1127]]
x_test = np.array(x_test)

# for i in range(len(train_df)):
#     temp = np.reshape(train_df[i],(1,7))
#     prediction_probility = model.predict(temp)
#     # predicted = model.predict(x_test)

#     if prediction_probility > 0.5:
#         print(i,1)

prediction_probility = model.predict(x_test)
prediction_probility

array([[ 0.36125985]], dtype=float32)

In [111]:
import numpy as np
from keras.models import load_model
import csv
import pandas as pd
import keras
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
import numpy as np

model = load_model('/Users/winnergogo/Desktop/DB/KHdjango/KH_project/KHtest/my_model.h5')

# person = [[92, 0, 3, 775, 0, 0, 313]]
# person = np.array(person)
# prediction_probility = model.predict(person)
# prediction_probility

for i in range(len(train_df)):
    temp = np.reshape(train_df[i],(1,7))
    prediction_probility = model.predict(temp)
    # predicted = model.predict(x_test)

    if prediction_probility > 0.5:
        print(temp,1)

[[  53    0    0   -3    0    0 1666]] 1
[[  54    0    0  529    1    0 1492]] 1
[[  46    0    1  179    1    0 1778]] 1
[[  56    0    0   45    0    0 1467]] 1
[[  41    0    0 1270    1    0 1389]] 1
[[  40    0    2   -4    1    0 2033]] 1
[[  43    2    3  205    1    0 1419]] 1
[[   39     1     3 45248     1     0  1623]] 1
[[  34    0    0  869    0    0 1677]] 1
[[  38    0    0  384    1    0 1906]] 1
[[  36    0    0  368    1    1 1597]] 1
[[  44    0    2  105    1    0 1529]] 1
[[  38    0    0  376    1    0 1521]] 1
[[  36    0    2  301    1    0 1581]] 1
[[  41    1    0  277    1    0 2177]] 1
[[  30    0    0  309    1    0 1574]] 1
[[  29    0    2  199    1    1 1689]] 1
[[  43    2    2  388    1    0 2087]] 1
[[  41    0    1  406    1    0 2462]] 1
[[  40    0    0   10    1    0 1692]] 1
[[  28    1    0 -197    1    0 2016]] 1
[[  27    0    0 1033    1    0 1713]] 1
[[  35    1    2 -202    1    0 1461]] 1
[[  31    0    2  713    1    0 1534]] 1
[[  33   

[[  40    0    0   42    0    0 1842]] 1
[[  35    2    2  434    1    0 1314]] 1
[[  43    0    2  423    0    0 3322]] 1
[[  33    1    2 6748    0    0 1579]] 1
[[  32    1    0 1732    1    0 1871]] 1
[[  31    2    2  254    0    0 1576]] 1
[[  60    0    1 1043    0    0 1364]] 1
[[  49    0    1  418    0    0 1559]] 1
[[  40    1    2  171    0    0 1241]] 1
[[  37    1    0  228    1    0 1740]] 1
[[  53    0    2  988    0    0 1408]] 1
[[  40    0    0 -432    1    1 1464]] 1
[[  34    1    0  666    0    0 1503]] 1
[[  30    1    2 -477    0    1 1532]] 1
[[  34    1    2  462    0    0 1877]] 1
[[  55    0    3  890    0    0 1329]] 1
[[  30    0    2  296    0    0 1809]] 1
[[  34    0    0 1035    0    0 1374]] 1
[[  36    2    0   54    1    0 1642]] 1
[[  53    0    1 5603    0    0 2372]] 1
[[  36    1    2 -103    1    1 3253]] 1
[[  48    1    3 1279    0    0 2429]] 1
[[  30    0    0 1664    1    0 2016]] 1
[[  30    0    0 1310    0    0 3284]] 1
[[  59    0    2

[[   41     0     0 14968     0     0  1360]] 1
[[  57    2    0 1088    0    0 1697]] 1
[[  24    1    0 1925    0    0 1363]] 1
[[  45    1    0  955    0    0 3785]] 1
[[  48    1    3 1819    0    0 1440]] 1
[[  28    1    0  127    0    0 1334]] 1
[[  24    1    2  393    0    0 1298]] 1
[[  34    1    2  549    0    0 1246]] 1
[[  40    0    2    0    0    0 1410]] 1
[[  38    0    0  557    1    0 1556]] 1
